### ISSUE TITLE
The tutorial doesn't render images correctly when read on github

### ISSUE THREAD

**Issue by felipefarinon** [uwerat/qskinny#414]
If you access https://github.com/uwerat/qskinny/blob/master/doc/tutorials/01-What-is-QSkinny.asciidoc you'll see that the images are not rendering. Was the tutorial meant to be read in another way, or is it broken?

![image](https://github.com/uwerat/qskinny/assets/17036813/0fb138c8-54f4-41ce-9358-555e6c90a1db)

**Comment by peter-ha** [comment]
Not sure if this is that important TBH, as long as they are rendering correctly on the homepage at https://qskinny.github.io/docs/tutorials/01-What-is-QSkinny/

**Comment by uwerat** [comment]
All links in the tutorials seem to have a wrong path - starting with ../images instead of ./images.
But why do some of the tutorials display the correct images then ?

The link for the Fendt tractor goes to some external page, that does not exist.

IMHO some of the images could be updated - f.e the one showing buttons in the squiek skin.
