### ISSUE TITLE
vs2017 Qt 5.11.2 msvc2017_64 compile error

### ISSUE THREAD

**Issue by danieljpb** [uwerat/qskinny#66]
In Visual Studio 2017 when I try to compile qskinny compile fine but squiekskin (necessary to compile the rest) get a error ( 'staticMetaObject' : definition of dllimport static data member not allowed):

qskinny-master\skins\squiek\generatedfiles\debug\moc_qsksquiekskinfactory.cpp(66): error C2491: 'QskSquiekSkinFactory::staticMetaObject': definición de miembro de datos estático dllimport no permitida (compilando archivo de origen QskSquiekSkinFactory.cpp)

qskinny-master\skins\squiek\generatedfiles\debug\moc_qsksquiekskin.cpp(65): error C2491: 'QskSquiekSkin::staticMetaObject': definición de miembro de datos estático dllimport no permitida (compilando archivo de origen QskSquiekSkin.cpp)

Best Regards

**Comment by uwerat** [comment]
My Spanish skills are limited, but it looks like being an issue with dllimport/dllexport. This is hidden behind QSK_EXPORT in QskGlobal.h. Then in src.pro you find DEFINES += QSK_MAKEDLL, so that dllexport is enabled, when building the qskinny lib.

The same has to be done for the other shared libraries, but of course using different defines - what is obviosly wrong at the moment. So f.e for building the squiek skin you need to have something like QSK_SQUIEK_EXPORT and QSK_SQUIEK_MAKEDLL.

Could you please add those definitions like in the other libs and check if this solves the problem ?

**Comment by uwerat** [comment]
I added several fixes for the dllimport/dllexport stuff - but totally untested as I don't have any Windows system here. Please give it a try and let me know if and what has been forgotten.

**Comment by danieljpb** [comment]
Perfect!!, Now compile fine, I am going to compile the examples, and let you know if there is any problem.

Thanks so much

**Comment by uwerat** [comment]
As all compilation problems seem to be solved I close this issue.
When running into runtime problems, don't hesitate to create new issues.
