### ISSUE TITLE
Please, make some tagged release

### ISSUE THREAD

**Issue by suy** [uwerat/qskinny#78]
Hello.

I've been following the project with interest for some time now, and I've attended Peter's talk at QtWS19. I see @peter-ha has posted a link to a video where the project is used (nice work, BTW!), so I wonder if it would now be possible to make some kind of tagged release, even if it's only alpha or tech preview.

I think that would help in getting started with it, as one could start playing with the library with a bit more confidence (that would be my case at least).

Thank you!

**Comment by uwerat** [comment]
The reason why I did not even make a 0.0 release yet is because I don't want to attract users before having these basics done:

- Doxygen API docs - at least for the C++ part
- finalizing the theming part ( setting up a skin is a pain )
- having at least one acceptable skin/theme

The reason why I don't have those yet is because they are not covered by the project  in the video. So this is something I have to do in my free time what naturally takes longer. Hope I will find the time in the next months and announce a release.
( Actually there are also a lot more controls implemented that are good enough for the application, but need to be polished to make it into qskinny )

Until then II can recommend qskinny to large projects, that have the time and resources to understand the architecture and its options. It will take longer to get things started, but in the end you will have a much faster and lightweight application..

Guess I should explain the state of the project on the project page.

**Comment by suy** [comment]
Thank you for the response. It helps to get the pulse of the state of the project, and what could follow next. Myself, I've been able to build the docs locally to start peeking at it, and since I want to experiment with Github's Actions, if time permits, I will try to setup an automatic build of the docs which might be published as GitHub Pages, or something else.

**Comment by uwerat** [comment]
The documentation is totally outdated and IMHO it does not make much sense to look at it at the moment. But there are 2 big other commercial projects - one that is seriously investigating qskinny, the other one already decided - that put the API docs high on top of my TODO list.

One interesting question here is qdoc vs. doxygen. Usually I would always prefer doxygen, but there is the specific problem, that parts of the documentation have to be created for C++ and QML. In the outdated docs you can see, that I tried to solve this with the code you find in tools/metadoxfilter. But I remember, that the maintainer of qdoc wrote on a mailinglist quite some time ago, that he wants to address this requirement.

On the other hand all ( = 100% ) of the projects being interested in qskinny I know of have the motivation of doing C++. That's why my priority is to have a good C++ APIs first. This will include ~90% of what you need for QML, but adding the last 10% has to be done later.

So I will probably focus on the C++ API for the documentation too and use doxygen for this as it is. Finding a solution for documentation of the QML API can be done later.

If you have more experience with qdoc or know of a solution how to do C++ and QML docs with doxygen, please let me know.

**Comment by uwerat** [comment]
We started working towards a first release:  https://github.com/uwerat/qskinny/milestone/2
