### ISSUE TITLE
QskTabBar bug

### ISSUE THREAD

**Issue by ovenpasta** [uwerat/qskinny#97]
I found a bug while adding a new tab to QskTabBar through QskTabView, in practice the tabs where disappearing after adding a new tab. I saw that adding update() to the insertTab method fixed the issue. 

```
int QskTabBar::insertTab( int index, QskTabButton* button )
{
    auto buttonBox = m_data->buttonBox;

    if ( index < 0 || index >= buttonBox->count() )
        index = buttonBox->count();

    if ( isComponentComplete() )
    {
        if ( count() == 0 )
        {
            m_data->currentIndex = 0;
            button->setChecked( true );
        }
    }

    buttonBox->insertItem( index, button );
    buttonBox->restack( m_data->currentIndex );

    if ( button->textOptions() != m_data->textOptions )
        button->setTextOptions( m_data->textOptions );

    m_data->connectButton( button, this, true );

    polish(); // ADD THIS TO FIX

    Q_EMIT countChanged( count() );

    return index;
}
```

**Comment by uwerat** [comment]
I added append/remove buttons to the tabview example to be able to debug the reason for the issue, but it does not happen there. In case you are not using the latest code from the master branch please verify if the problem still exists. Otherwise it would help if you could modify the tab view example so that it demonstrates the problem.

If everything works as expected the suggested fix is not necessary as inserting a button into the internal buttonBox should lead to  a QEvent::LayoutRequest, that finallly will end up somehow in the class that is responsible for recalculating the layout. Inserting a polish call manually means that something goes wrong with propagating/processing layout requests in general that needs to be understood.

**Comment by uwerat** [comment]
As there is no further response I guess the problem is gone.
